#!/bin/bash

rm hat_brick.eep spi.dtb ../software/src/eeprom_data.c

dtc -@ -I dts -O dtb -o spi.dtb spi.dts
eepmake eeprom_settings.txt hat_brick.eep spi.dtb

echo "// generated by ../../rpi/build.sh" > ../software/src/eeprom_data.c
echo "#include <stdint.h>" >> ../software/src/eeprom_data.c
python3 -c "print('const uint8_t eeprom_data[] = ' + str(list(open('hat_brick.eep', 'rb').read())).replace('[', '{').replace(']', '}') + ';')" >> ../software/src/eeprom_data.c
