#!/usr/bin/env python

import sys
import string

with open('hat_brick_ds1307.eep', 'rb') as f:
    ds1307 = f.read()

with open('hat_brick_pcf8523.eep', 'rb') as f:
    pcf8523 = f.read()

if len(ds1307) != len(pcf8523):
    print("hat_brick_ds1307.eep and hat_brick_pcf8523.eep size are not the same!")
    sys.exit(1)

assignments = []

last_i = -1
for i, tup in enumerate(zip(ds1307, pcf8523)):
    left, right = tup
    if left != right:
        # add empty line between patch blocks
        if last_i != -1 and last_i != i - 1:
            assignments.append("\\");
        last_i = i

        r = f"0x{right:x}" if not chr(right) in string.printable else f"'{chr(right)}'"
        assignments.append(f"\teeprom_data[0x{i:x}] = {r}; \\")

content = """// generated by ../../rpi/create_eeprom_data_c.py
#include <eeprom_data.h>

uint8_t eeprom_data[] = {{{data}}};
""".format(data=",".join([str(x) for x in ds1307]))

header = """// generated by ../../rpi/create_eeprom_data_c.py
#include <stdint.h>

extern uint8_t eeprom_data[];

#define EEPROM_PATCH_TO_PCF8523() \\
{assignments}

""".format(assignments="\n".join(assignments))

with open("../software/src/eeprom_data.c", "w") as f:
    f.write(content)

with open("../software/src/eeprom_data.h", "w") as f:
    f.write(header)
