// generated by ../../rpi/create_eeprom_data_c.py
#include <stdint.h>

extern uint8_t eeprom_data[];

#define EEPROM_PATCH_TO_PCF8523() \
	eeprom_data[0x2c5] = 'p'; \
	eeprom_data[0x2c6] = 'c'; \
	eeprom_data[0x2c7] = 'f'; \
	eeprom_data[0x2c8] = '8'; \
	eeprom_data[0x2c9] = '5'; \
	eeprom_data[0x2ca] = '2'; \
	eeprom_data[0x2cb] = '3'; \
	eeprom_data[0x2cc] = '@'; \
	eeprom_data[0x2cd] = '6'; \
	eeprom_data[0x2ce] = '8'; \
\
	eeprom_data[0x2dd] = 'n'; \
	eeprom_data[0x2de] = 'x'; \
	eeprom_data[0x2df] = 'p'; \
	eeprom_data[0x2e0] = ','; \
	eeprom_data[0x2e1] = 'p'; \
	eeprom_data[0x2e2] = 'c'; \
	eeprom_data[0x2e3] = 'f'; \
	eeprom_data[0x2e4] = '8'; \
	eeprom_data[0x2e5] = '5'; \
	eeprom_data[0x2e6] = '2'; \
\
	eeprom_data[0x2e8] = 0x0; \
	eeprom_data[0x2e9] = 0x0; \
\
	eeprom_data[0x4eb] = 0xdf; \
	eeprom_data[0x4ec] = ';'; \

